# Generated by Django 3.2.7 on 2021-09-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_regtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
