# Generated by Django 3.2.7 on 2021-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210917_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num',
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='regtime',
            field=models.TimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
