# Generated by Django 3.2.7 on 2021-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('coin', models.IntegerField(default=0)),
                ('pos', models.CharField(default='0.0-0.0', max_length=20)),
            ],
        ),
    ]
