# Generated by Django 3.2.7 on 2021-09-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='pos',
            field=models.CharField(default='0-0', max_length=20),
        ),
    ]
