# Generated by Django 3.2.7 on 2021-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0002_alter_egg_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='pos',
            field=models.CharField(default='0/0', max_length=20),
        ),
    ]
