# Generated by Django 3.2.7 on 2021-09-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingame',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('posx', models.IntegerField(default=0)),
                ('posy', models.IntegerField(default=0)),
                ('posz', models.IntegerField(default=0)),
                ('rotx', models.IntegerField(default=0)),
                ('roty', models.IntegerField(default=0)),
                ('rotz', models.IntegerField(default=0)),
            ],
        ),
    ]
