# Generated by Django 3.2.7 on 2021-09-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_ingame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingame',
            name='posx',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='posy',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='posz',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='rotx',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='roty',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='rotz',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
