# Generated by Django 3.2.7 on 2021-09-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210913_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='user',
            name='player',
            field=models.IntegerField(default=0),
        ),
    ]
