# Generated by Django 3.2.7 on 2021-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210917_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unlock',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
