# Generated by Django 3.2.7 on 2021-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastpos',
            field=models.CharField(default='0,4,-69', max_length=15),
        ),
    ]
