# Generated by Django 3.2.7 on 2021-09-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_lastpos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastpos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unlock',
        ),
        migrations.AddField(
            model_name='user',
            name='badge_state',
            field=models.CharField(default='0000000', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='badge_subinfo',
            field=models.CharField(default='0/0', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='character_unlock',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='ecomileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='furniture_state',
            field=models.CharField(default='000000000000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='inventory_state',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='mission_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='museum_unlock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='smartfarm_state',
            field=models.CharField(default='0/0/00-00-00-00-00/0/0/00-00-00-00-00', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='submission_state',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
