# Generated by Django 3.2.7 on 2021-09-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210928_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energy_item_unlck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='soil_item_unlock',
            field=models.IntegerField(default=0),
        ),
    ]
