# Generated by Django 3.2.7 on 2021-09-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_energy_item_unlck_user_energy_item_unlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingame',
            name='posx',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='posy',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='posz',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='rotx',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='roty',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='rotz',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='inventory_state',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
