# Generated by Django 3.2.7 on 2021-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210930_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge_subinfo',
            field=models.CharField(default='0/0/0-0-0', max_length=10),
        ),
    ]
