# Generated by Django 3.2.7 on 2021-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_badge_subinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge_subinfo',
            field=models.CharField(default='0/0/000', max_length=10),
        ),
    ]
