# Generated by Django 3.2.7 on 2021-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='regtime',
            field=models.TimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
