# Generated by Django 3.2.7 on 2021-09-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_regtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='regtime',
            field=models.TimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
